[project]
name = "flowstab"
description = "Framework for dynamic community detection in temporal networks."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name="Alexandre Bovet", email="alexandre.bovet@uzh.ch"},
]
classifiers = [
  "Programming Language :: Python :: 3",
]
dependencies = [
    "hickle>=5.0.3",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "psutil>=7.2.2",
    "scipy>=1.15.3",
    "stochmat @ git+https://github.com/bovet-research-group/stochmat.git",  # add `@1.0.0-rc4` to pin to a version
    "tempnet @ git+https://github.com/bovet-research-group/temporal-networks.git",
]
dynamic = ["version"]

[project.optional-dependencies]
mkl = [
  "stochmat[mkl] @ git+https://github.com/bovet-research-group/stochmat.git@1.0.0-rc2",
]

[dependency-groups]
testing = [
  "pytest>=9.0.2",
  "pytest-cov>=7.1.0",
  "pytest-memray>=1.8.0",
  "ruff>=0.15.7",
]
docs = [
  "insegel>=1.3.1",
  "myst-parser>=4.0.1",
  "sphinx>=8.1.3",
  "sphinx-autoapi>=3.8.0",
]
dev = [
  { include-group = "testing" },
  { include-group = "docs" },
]

[project.scripts]
run_clusterings = "flowstab.scripts.run_clusterings:main"
run_cov_integrals = "flowstab.scripts.run_cov_integrals:main"
run_laplacians_transmats = "flowstab.scripts.run_laplacians_transmats:main"

[project.urls]
Homepage = "https://github.com/alexbovet/flow_stability"
Repository = "https://github.com/alexbovet/flow_stability.git"

# Specify the packages to install
[tool.hatch.build.targets.wheel]
packages = ["src/flowstab"]

# Use git tags as version for the package
[tool.hatch.version]
source = "vcs"

# (Optional to set the version also Python-style)
[tool.hatch.build.hooks.vcs]
version-file = "src/flowstab/_version.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.coverage.run]
relative_files = true
source = ["src"]
omit = [
  "tests",
  "*__init__.py",
  "*/_version.py",
]

[tool.coverage.paths]
source = [
    "src/flowstab",
]

# This is for the linting with ruff
[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
# T201: complain about print statements
ignore = ["T201"]

[tool.ruff.lint.per-file-ignores]
# we want to accept import violations in special contexts
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

[build-system]
requires = [
  "hatchling",
  "hatch-vcs",
]
build-backend = "hatchling.build"
